# 生产环境
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://120.24.29.192:3306/zazbug?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: changwei1994mysql
server:
  port: 18088
jwt:
  secret: secret
  expiration: 7200000
  token: Authorization
web:
  # 上传图片路径
  upload-path: "/usr/local/Temp/upload/"
  # 请求路径
  http-path: "/image/**"
  # 映射路径
  file-path: "file:/usr/local/Temp/upload/"
  # ip地址
  ip: "120.24.29.192"

