spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/zazbug?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: root
server:
  port: 18088
jwt:
    secret: secret
    expiration: 7200000
    token: Authorization
